MAIL_USERNAME = 'WRITE_DOWN_YOUR_ADDRESS'
MAIL_PASSWORD = 'WRITE_DOWN_YOUR_API_PASS'

STRIPE_SECRET_KEY = 'WRITE_DOWN_YOUR_STRIPE_KEY'
STRIPE_PUBLISHABLE_KEY = 'WRITE_DOWN_YOUR_STRIPE_PUBLISHABLE_KEY'
